apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # this selctor selects template.metadata.labels app:mongo ..... for connect all the pods 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
